name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Install application dependencies
        run: yarn

      - name: Build application
        run: yarn build:staging

      - name: Unit test helper functions
        run: yarn test:unit:helpers

      - name: Unit test components
        run: yarn test:unit:components

      - name: Start application
        run: yarn start

      - name: E2E tests
        env:
          SECRET_WORDS: ${{ secrets.SECRET_WORDS }}
          NETWORK_NAME: ${{ secrets.NETWORK_NAME }}
          RPC_URL: ${{ secrets.RPC_URL }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
        run: xvfb-run --auto-servernum yarn test:e2e:ci
